name: WildSex
main: com.cemgokmen.wildsex.WildSex
author: sultanskyman
version: '${project.version}'
commands:
   wildsex:
      description: Returns the number of seconds left until the next time animals are randomly bred.
      usage: /<command>
