language: java
sudo: false
install:
  - wget https://drone.io/github.com/bergerhealer/BKCommonLib/files/target/BKCommonLib.jar
  - mvn install:install-file -Dfile=BKCommonLib.jar
deploy:
  provider: releases
  api_key:
    secure: aMJRj29EMLocCiy7gmBnYxI/A1vR8Tu1q9PzzVdgcZJXSzSFHFDmhgDzOqgGIpEmlAMMLHPEFZGnwen8NLeMM6eyRqbDqavmWddVSz0L5hf8YXsAAWEpjjfIspTWTxGtM7xIAaBZ9uFKCLpSn9kXP4W2OB67L4Hr7V8wN4+/ET0=
  file: target/WildSex.jar
  on:
    tags: true
    repo: sultanskyman/WildSex
