language: java
jdk:
  - oraclejdk8
sudo: false
install:
  - mvn install
deploy:
  provider: releases
  api_key:
    secure: aMJRj29EMLocCiy7gmBnYxI/A1vR8Tu1q9PzzVdgcZJXSzSFHFDmhgDzOqgGIpEmlAMMLHPEFZGnwen8NLeMM6eyRqbDqavmWddVSz0L5hf8YXsAAWEpjjfIspTWTxGtM7xIAaBZ9uFKCLpSn9kXP4W2OB67L4Hr7V8wN4+/ET0=
  file: target/WildSex.jar
  on:
    tags: true
    repo: sultanskyman/WildSex
